### ISSUE TITLE
Sidebar “Mapas”

### ISSUE THREAD

**Issue by i62lotor** [geowe/RTCMapping#10]
Mostrar las dos capas por defecto (la de edición y OSM) Podrán ocultarse, pero en esta versión no se podrán eliminar.

**Comment by i62lotor** [comment]
Rrelacionado con #6 
Está listo para revisión

**Comment by jmmluna** [comment]
Todo correctísimo!!

**Comment by sigdeletras** [comment]
En la versión disponible, no funciona la Sidebar. Probada con Google Chrome Versión 65.0.3325.181

**Comment by sigdeletras** [comment]
Listo. Estaba probando la URL antigua.
