### ISSUE TITLE
Crear página de ayuda

### ISSUE THREAD

**Issue by i62lotor** [geowe/RTCMapping#12]
Es necesario crear una página html de ayuda de usuario.
Esta página se enlazará desde el elemento Ayuda del sidebar 

Podría ser una página dentro de www.geowe.org o una independiente en rtcm-geowe.org/ayuda (por ejemplo)

**Comment by i62lotor** [comment]
la ayuda colgaría de la url: rtcm.geowe.org/ayuda

**Comment by sigdeletras** [comment]
Al final la ayuda se creará en la Wiki del repositorio. [https://github.com/geowe/RTCMapping/wiki](https://github.com/geowe/RTCMapping/wiki)

**Comment by sigdeletras** [comment]
Para almacenar las imágenes de la Wiki se ha creado la carpeta help/IMG

**Comment by sigdeletras** [comment]
Habría que cambiar la URL de Ayuda dentro del Sidebar para que apunte a la dirección de la Wiki.

**Comment by i62lotor** [comment]
Estoy en ello.

**Comment by i62lotor** [comment]
Ya se enlaca desde el sidebar. En cuanto se despliegue la nueva versión estará disponible.
Muy bien @sigdeletras.
Si te parece cierro esta tarea. Si hace falta se van creando otras, para ir completando la wiki
