### ISSUE TITLE
Definir estilo para geometría punto seleccionada

### ISSUE THREAD

**Issue by sigdeletras** [geowe/RTCMapping#13]
Al usar la herramienta de Selección, la geometría de tipo punto seleccionada no tiene estilo definido o es incorrecto por lo que no aparece. No ocurre en líneas ni en polígonos, aunque en esta última no está definido el relleno del polígono seleccionado.

**Comment by i62lotor** [comment]
Solucionado en rafa-dev.

**Comment by jmmluna** [comment]
Probado y funcionando correctamente
