### ISSUE TITLE
Añadir licencia de OpenStreetMap en mapa principal

### ISSUE THREAD

**Issue by sigdeletras** [geowe/RTCMapping#15]
La información está disponible en el siguiente enlace [https://www.openstreetmap.org/copyright/es](https://www.openstreetmap.org/copyright/es)

**Comment by i62lotor** [comment]
La atribución está añadida, pero se queda debajo del div del pie.
Pasa lo mismo que con la cabecera. El mapa sigue estándo por debajo.
Por ahora para esta versión veo suficiente modificar el valor por defecto de la posición.

Quizá lo podamos poner en el pie en una próxima versión. 
El cambio está listo para revisión en rafa-dev.

**Comment by jmmluna** [comment]
Probado y funcionando correctamente
