### ISSUE TITLE
Añadir capa base PNOA o no

### ISSUE THREAD

**Issue by sigdeletras** [geowe/RTCMapping#20]
Creo que sería un aporte, al menos para usuarios de España, añadir como capa base el WMS del PNOA. ¿Además de la base de Google Maps existe alguna otra ortoimagen escala mundial que se pudiera usar y tenga una licencia que lo permita? Habría que mirarlo

**Comment by i62lotor** [comment]
Para la versión MVP acordamos la capa base de OSM.
Para versiones sucesivas creo que comentamos ofrecer un catálogo de capas WMS, WMTS, WFS, o lo que se disponga.
Para usar algunas capas requerira el uso de "Key". Habra que ver en cada caso.
Por tanto este issue se puede quedar en la lista de previsiones para la siguiente versión.

**Comment by geowe** [comment]
Se han puesto como capas de prueba en la versión de demo el catastro de España y Bing Aerial
