### ISSUE TITLE
Herramienta localizacion

### ISSUE THREAD

**Issue by i62lotor** [geowe/RTCMapping#24]
Implementar funcionalidad geolocalización por topónimos.

**Comment by i62lotor** [comment]
Para esta versión se implementara la consulta contra el servicio Nominatim de OSM.
El uso previsto en la demo es bajo

**Comment by i62lotor** [comment]
faltaría notificar cuando se produce algún error, o no se encuentra la dirección indicada, limpiar la cadena de búsqueda al pulsar la lupa, que busque al pulsar intro, que muestre loading mientras busca,

**Comment by i62lotor** [comment]
Notifica la geolocalización, si no encuentra nada o si se produce un error.
Busca al pulsar enter.
Se limpia la cadena al pulsar en el input.
He cambiado la posición de la búsqueda, y he usado el logo de OSM. La licencia de OSM Nominatim indica que se debe identificar su uso..
Se podría quitar el botón de buscar.

**Comment by sigdeletras** [comment]
Ya que se ha modificado la ubicación de la herramienta, creo que para que visualmente destaque más se podría ajustar el padding (alto) de la caja para que contraste con el fondo azul de footer
