### ISSUE TITLE
Herramienta buffer

### ISSUE THREAD

**Issue by i62lotor** [geowe/RTCMapping#25]
Herramienta para crear área de influencia de un elemento

**Comment by i62lotor** [comment]
Pendiente de comprobar valores de cadenas en el valor del buffer. Solo aceptar valores numéricos

**Comment by i62lotor** [comment]
Sale el diálogo del buffer aunque no haya ningún elemento seleccionado.
Creo que debemos homogenizar la funcionalidad, para que las herramientas sean igual. Quiero decir, que se comporten igual que la de borrar por ejemplo.

**Comment by sigdeletras** [comment]
Al generar el buffer, elimina u oculta la geometría seleccionada para el proceso.

**Comment by i62lotor** [comment]
La geometria generada reemplaza la existente.
Para cambiar la funcionalidad lo debatimos en otro issue.
Gracias

**Comment by sigdeletras** [comment]
Entonces sería más una herramienta de dibujo que de geoproceso no?

**Comment by i62lotor** [comment]
Con los cambios en la interfaz de usuario quedará mas clara esta funcionalidad del MVP.
