### ISSUE TITLE
Obtener la url  cuando está en modo Compartido

### ISSUE THREAD

**Issue by sigdeletras** [geowe/RTCMapping#33]
Cuando el proyecto se encuentra en modo Compartir, no se puede obtener la URL. Puede ocurrir que hayamos perdido la url y necesitemos mandarla a nuevos usuarios

**Comment by sigdeletras** [comment]
Disponible en sidebar según changelog. En mi opinión queda un poco escondida.

**Comment by sigdeletras** [comment]
Hay el revisar la ventana. En portátil (resolución 1366 x 798) no aparece correctamente.
![image](https://user-images.githubusercontent.com/4746157/39172712-dea25a28-47a2-11e8-9c56-64d7dcc2ef40.png)

**Comment by geowe** [comment]
Solucionado en la última version
