### ISSUE TITLE
Herramienta info

### ISSUE THREAD

**Issue by sigdeletras** [geowe/RTCMapping#36]
- El panel actual podría reducirse un poco. Ocupa gran parte de la pantalla, del mapa y no permite visualizar los datos geográficos (portátil).
- Es necesario poder identificar el registro de la tabla son su representación geográfica. Ahora no están sincronizados, al menos visualmente.
- La herramienta de info es más un acceso a la tabla de atributos de toda la capa. Sería interesante añadir un función de información por elemento de tipo popup.

**Comment by jmmluna** [comment]
Ya se ha mejorado todo en la Demo version - 1.0 a falta del popup de la información del elemento, en próximas versiones se tendrá en cuenta
