### ISSUE TITLE
Consulta sobre atributos alfanuméricos

### ISSUE THREAD

**Issue by i62lotor** [geowe/RTCMapping#39]
Buenas tardes: Les escribo desde Argentina, quiero hacerles una consulta acerca de RTC Mapping. Necesito hacer la edición colaborativa de unos lotes de algodón, para registrar variables relacionadas al estado del cultivo. Se puede crear un proyecto colaborativo de tal forma que al pasarle el link a los técnicos de terreno, puedan editar la capa, básicamente es cargar una fecha de actualización y unos atributos relacionados al estado fenológico y a la presencia de insectos. Agradezco desde ya su respuesta. Saludos cordiales

_Originally posted by @lopezjuana in https://github.com/geowe/RTCMapping/issues/34#issuecomment-611184908_

**Comment by i62lotor** [comment]
@lopezjuana los atributos alfanuméricos de cada capa los puede crear el usuario que ha creado la sesión colaborativa. Cuando el resto de colaboradores reciben el link, esos atributos existen y los pueden rellenar sin ningún problema.

Espero te sirva de ayuda.

**Comment by lopezjuana** [comment]
Buenas tardes @i62lotor: Agradezco su respuesta. Efectivamente cargué mi archivo desde el github y me permitió editarlo desde la URL. 
Muchas gracias, saludos cordiales

**Comment by sitse** [comment]
Buenas noches @i62lotor nuevamente tuve inconvenientes para compartir el archivo, agrego un mapa desde esta URL https://raw.githubusercontent.com/sitse/Proyectos_SIG/master/Capas/Lotes_algodon.geojson consulto la tabla de atributos y me aparece como no compartido. En el momento de acceder a través de la URL para editar la capa no se visualiza. Adjunto una captura de pantalla. No sé que paso estaré haciendo mal. Muchas gracias. Saludos
![Captura_Mapping](https://user-images.githubusercontent.com/63485873/79035565-4455b580-7b96-11ea-91f6-ae062700d1b3.PNG)

**Comment by i62lotor** [comment]
Hola @lopezjuana, parece que no has pulsado en compartir. Por eso has cargado la capa, pero no se ha compartido ningún elemento (están de color azul).
He probado a cargar el fichero de github que indica y al tener la sesión de mapeo compartida se ve en verde. Mira la imagen adjunta
![Screenshot_2020-04-11 RTC Mapping by GeoWE](https://user-images.githubusercontent.com/17040784/79047553-a0145300-7c17-11ea-8132-973b3a967363.png)

en este caso se ven los elementos verdes (los que ha compartido el usuario, además de uno rojo que ha creado un colaborador (lo he simulado yo abriendo rtcm en dos navegadores).

Acabamos de publicar este post [Recomendaciones para realizar un Mapeo Colaborativo en Tiempo Real](http://geowegis.blogspot.com/2020/04/recomendaciones-para-realizar-un-mapero.html)que puede ayudarte a entender el funcionamiento.

Espero que te sea de ayuda.
Si necesitas algo mas no dudes en comentarlo.

**Comment by lopezjuana** [comment]
Buenos días @i62lotor: Efectivamente compartí la URL y luego agregué la
capa a Editar. De este modo, quedó habilitada la capa para edición. Muchas
gracias por las recomendaciones, trabajo en INTA (Instituto Nacional de
Tecnología Agropecuaria) y recomendaré el uso de GeoWE, felicitaciones al
grupo de desarrollo. Saludos cordiales.

**Comment by i62lotor** [comment]
Estupendo.
Cierro este issue.
☺️

**Comment by sitse** [comment]
Buenas tardes Rafael, cómo está? Le comento que realizaremos un Taller de
mapeo colaborativo, utilizando RTC Mapping el día 16 de Junio. También se
está planificando realizar la ubicación y caracterización de zonas
socio-económicamente más vulnerables. Necesito consultarle unas cuestiones
relacionadas al uso de la herramienta:
1) Cuánto tiempo permanece abierta una sesión de edición colaborativa? Hice
algunas pruebas y me pasó que al volver a cargar el link unos días después,
ya no me mostraba la capa que estaba en edición.
2) Es más seguro cargar la capa desde un Github o crearla a la capa desde
la aplicación?
3) Hay alguna experiencia de mapeo, cargando como campos adicionales fotos
de los objetos que se relevan?
4) Tienen pensado incorporar la posibilidad de tomar las coordenadas,
utilizando la ubicación de un dispositivo móvil?
Saludos cordiales, Juana

**Comment by lopezjuana** [comment]
Muchas gracias, cuánto tiempo puede estar abierta la sesión de edición? En
el caso de volver a conectarme y no estar la capa, se pueden recuperar las
ediciones hechas desde algún sitio?

**Comment by i62lotor** [comment]
Hola, Juana.
Respondo a tus  preguntas en el issue #51

**Comment by sitse** [comment]
Buenos días. Muchas gracias por su respuesta. Si les es de utilidad, les enviaremos un breve informe sobre la experiencia del Taller de Mapeo colaborativo. Saludos cordiales

**Comment by i62lotor** [comment]
Sería estupendo que nos contaras vuestra experiencia.
Un saludo
