### ISSUE TITLE
Sidebar enlaces

### ISSUE THREAD

**Issue by i62lotor** [geowe/RTCMapping#6]
Completar los enlaces indicados en el sidebar

**Comment by i62lotor** [comment]
**CONDICIONES DE USO:**  enlace externo a http://www.geowe.org/index.php?id=termsOfUse

**Comment by i62lotor** [comment]
**CONTACTO:** enlace externo a http://www.geowe.org/index.php?id=contacto
He modificado la página de contacto para incluir RTCMapping.

**Comment by i62lotor** [comment]
**Visibilidad de las capas:** para esta versión se podrán ocultar las capas (y volverlas a mostrar). está a medio implementar en el branch rafa-dev

**Comment by i62lotor** [comment]
implemenado ocultar/mostrar capas: la de edición y la capa base OSM.

Lo voy a poner para revisión y divido esta tarea en otras mas, para no acumular mucho.

**Comment by jmmluna** [comment]
Se cambia en el menú el nombre de Sugerencias por el de Contacto. Todo revisado y funcionando correctamente.
