### ISSUE TITLE
Herramienta Modificar geometría

### ISSUE THREAD

**Issue by jmmluna** [geowe/RTCMapping#7]
implementación colaborativa

**Comment by i62lotor** [comment]
Al modificar la geometría se envía al resto de colaboradores.

**Comment by i62lotor** [comment]
Después de varias pruebas he realizado algunas modificaciones para  los casos de elementos que no se han compartido.
En el caso de modificar la geometría de elementos no compartidos, estos no se transmitirán al resto de colaboradores.
Cada elemento tendrá por defecto las siguientes propiedades:
 `"properties":{"nick":"user-2", "shared":true,"modified":true}`

donde:
- **nick** : es el usuario que ha realizado la última operación sobre el elemento (crearlo, modificarlo)
- **shared**: true = el elemento ha sido compartido
- **modified**: true = el elemento ha sido modficado
