### ISSUE TITLE
Sidebar (continuación)

### ISSUE THREAD

**Issue by i62lotor** [geowe/RTCMapping#9]
Continuación del issue #6 
Implementar funcionalidad pendiente en el sidebar:

**Ayuda:** enlace externo a una página de ayuda.

**Colaboradores:** indicará con cuantos colaboradores está compartiendo el mapa en ese momento.

**Estado:** indicará si está compartiendo el mapa.

**Guardar:** Añadir al sidebar un nuevo elemento que haga la funcionalidad de guardar(descargar) la capa de edición en formato geojson (WGS84) issue #11 .

**Añadir mapas:** esta funcionalidad no está previsa para la versión MVP. Se puede poner un mensaje indicándolo.

**Comment by i62lotor** [comment]
incluido el enlace externo a la ayuda: http://rtcm.geowe.org/ayuda.
Habría que completar la web de ayuda. Ahora mismo hay un index de ejemplo

**Comment by sigdeletras** [comment]
Modificar "Open Street Map" por "OpenStreetMap".

**Comment by i62lotor** [comment]
sidebar lista para revisión en rafa-dev.
Faltaría la opción de "añadir mapas". Ya se implementará cuando corresponda. Para el MVP no está contemplado.

**Comment by jmmluna** [comment]
Ya se encuentra operativo el enlace de ayuda a la wiki:  http://rtcm.geowe.org/ayuda. Se modificó "Open Street Map" por OSM

**Comment by jmmluna** [comment]
Probado y funcionando correctamente.
